# Generated by Django 2.1.7 on 2019-05-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('progress', models.FloatField(default=0.0)),
                ('step', models.CharField(default='', max_length=100)),
                ('time_started', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(blank=True, default=None, null=True)),
                ('time_completed', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
