# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lexicon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=100)),
                ('lexicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lm.Lexicon')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wrd', models.CharField(max_length=100)),
                ('lexicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lm.Lexicon')),
                ('suggestionset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lm.SuggestionSet')),
            ],
        ),
    ]
