# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_type', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_set', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptualiser.Concept')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField()),
                ('term', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_author_relation_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TermConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptualiser.Concept')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptualiser.Term')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='descriptive_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptualiser.Term'),
        ),
    ]
