DEFAULT_REPLACE_MISSPELLED_NAMES = True
DEFAULT_REPLACE_SINGLE_LAST_NAMES = True
DEFAULT_REPLACE_SINGLE_FIRST_NAMES = True
DEFAULT_MISSPELLING_THRESHOLD = 0.9
DEFAULT_MIMIC_CASING = True
DEFAULT_AUTO_ADJUST = False

DEFAULT_CONSISTENT_REPLACEMENT = True
