# Generated by Django 2.2.24 on 2021-10-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crf_extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crfextractor',
            name='confusion_matrix',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AddField(
            model_name='crfextractor',
            name='f1_score',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='crfextractor',
            name='precision',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='crfextractor',
            name='recall',
            field=models.FloatField(default=None, null=True),
        ),
    ]
