# Generated by Django 2.2.24 on 2021-10-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crf_extractor', '0002_auto_20211008_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crfextractor',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='crfextractor',
            name='c2',
        ),
        migrations.AddField(
            model_name='crfextractor',
            name='best_c1',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='crfextractor',
            name='best_c2',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='crfextractor',
            name='c_values',
            field=models.TextField(default='[0.001, 0.1, 0.5]'),
        ),
    ]
