# Generated by Django 2.2.28 on 2022-04-26 08:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crf_extractor', '0004_auto_20220412_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crfextractor',
            name='context_feature_extractors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('isupper', 'isupper'), ('istitle', 'istitle'), ('hasdigit', 'hasdigit'), ('strlength', 'strlength')], max_length=34),
        ),
        migrations.AlterField(
            model_name='crfextractor',
            name='feature_extractors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('isupper', 'isupper'), ('istitle', 'istitle'), ('hasdigit', 'hasdigit'), ('strlength', 'strlength')], max_length=34),
        ),
    ]
