# Generated by Django 2.1.13 on 2019-11-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggergroup',
            name='num_tags',
            field=models.IntegerField(default=0),
        ),
    ]
