# Generated by Django 2.1.7 on 2019-11-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0002_taggergroup_num_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagger',
            name='stop_words',
            field=models.TextField(default=''),
        ),
    ]
