# Generated by Django 2.1.13 on 2019-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0003_auto_20191113_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagger',
            name='classifier',
            field=models.CharField(default='Logistic Regression', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tagger',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tagger',
            name='vectorizer',
            field=models.CharField(default='Hashing Vectorizer', max_length=1000),
        ),
        migrations.AlterField(
            model_name='taggergroup',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='taggergroup',
            name='fact_name',
            field=models.CharField(max_length=1000),
        ),
    ]
