# Generated by Django 2.1.7 on 2019-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0003_auto_20191113_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='fact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
