# Generated by Django 2.1.7 on 2019-11-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0004_auto_20191121_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='num_negatives',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tagger',
            name='num_positives',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
