# Generated by Django 2.1.14 on 2019-11-26 10:01
import json

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tagger', '0001_initial_squashed_0006_tagger_model_size'),
    ]

    operations = [

        migrations.AddField(
            model_name='tagger',
            name='model',
            field=models.FileField(default=None, null=True, upload_to='data/models/taggers', verbose_name=''),
        )
    ]
