# Generated by Django 2.1.13 on 2019-11-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0006_tagger_model_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='fact_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
