# Generated by Django 2.1.7 on 2019-12-16 11:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0009_remove_location_json_path_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='indices',
            field=multiselectfield.db.fields.MultiSelectField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='tagger',
            name='model',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name=''),
        ),
    ]
