# Generated by Django 2.1.7 on 2020-01-29 07:50

from django.db import migrations
import toolkit.multiselectfield


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0010_auto_20191216_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagger',
            name='indices',
            field=toolkit.multiselectfield.PatchedMultiSelectField(default=None, max_length=200),
        ),
    ]
