# Generated by Django 2.2.11 on 2020-03-09 14:30
import json

from django.db import migrations, models


def data_migration(apps, schema_editor):
    Tagger = apps.get_model('tagger', 'Tagger')
    for tagger in Tagger.objects.all():
        indices = list(tagger.indices)
        tagger.keeper = json.dumps(indices)
        tagger.save()


def final_solution(apps, schema_editor):
    Tagger = apps.get_model('tagger', 'Tagger')
    Index = apps.get_model('elastic', 'Index')

    for tagger in Tagger.objects.all():
        indices = json.loads(tagger.keeper)
        for index_name in indices:
            i, is_created = Index.objects.get_or_create(name=index_name)
            tagger.indices.add(i)
        tagger.save()


class Migration(migrations.Migration):
    dependencies = [
        ('elastic', '0003_index'),
        ('tagger', '0011_auto_20200129_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='keeper',
            field=models.TextField(default="[]"),
        ),

        migrations.RunPython(data_migration),

        migrations.RemoveField(
            model_name='tagger',
            name='indices',
        ),
        migrations.AddField(
            model_name='tagger',
            name='indices',
            field=models.ManyToManyField(to='elastic.Index'),
        ),

        migrations.RunPython(final_solution),

        migrations.RemoveField(
            model_name='tagger',
            name='keeper',
        ),
    ]
