# Generated by Django 2.1.15 on 2020-03-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0012_auto_20200309_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='lemmatize',
            field=models.BooleanField(default=False),
        ),
    ]
