# Generated by Django 2.2.17 on 2020-12-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0013_model_path_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='fact_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
