# Generated by Django 2.2.17 on 2020-12-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0014_tagger_fact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagger',
            name='num_negatives',
        ),
        migrations.RemoveField(
            model_name='tagger',
            name='num_positives',
        ),
        migrations.AddField(
            model_name='tagger',
            name='num_examples',
            field=models.TextField(default='{}', null=True),
        ),
    ]
