# Generated by Django 2.2.17 on 2021-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0015_auto_20201201_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='confusion_matrix',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
