# Generated by Django 2.2.17 on 2021-01-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0016_tagger_confusion_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='snowball_language',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
