# Generated by Django 2.2.18 on 2021-02-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210126_1041'),
        ('tagger', '0018_tagger_scoring_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggergroup',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task'),
        ),
    ]
