# Generated by Django 2.2.19 on 2021-03-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0019_taggergroup_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagger',
            name='stop_words',
            field=models.TextField(default='[]'),
        ),
    ]
