# Generated by Django 2.2.19 on 2021-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0021_tagger_ignore_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='detect_lang',
            field=models.BooleanField(default=False),
        ),
    ]
