# Generated by Django 2.2.19 on 2021-04-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0022_tagger_detect_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagger',
            name='balance_to_max_limit',
            field=models.BooleanField(default=False),
        ),
    ]
