# Generated by Django 2.2.20 on 2021-04-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0023_auto_20210420_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagger',
            name='snowball_language',
            field=models.CharField(choices=[(None, None), ('arabic', 'arabic'), ('estonian', 'estonian'), ('catalan', 'catalan'), ('danish', 'danish'), ('dutch', 'dutch'), ('english', 'english'), ('finnish', 'finnish'), ('french', 'french'), ('german', 'german'), ('hungarian', 'hungarian'), ('italian', 'italian'), ('lithuanian', 'lithuanian'), ('norwegian', 'norwegian'), ('portuguese', 'portuguese'), ('romanian', 'romanian'), ('russian', 'russian'), ('spanish', 'spanish'), ('swedish', 'swedish'), ('turkish', 'turkish')], default=None, max_length=1000, null=True),
        ),
    ]
