# Generated by Django 2.2.20 on 2021-05-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0024_auto_20210421_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='tagger_groups',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
