# Generated by Django 2.2.20 on 2021-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0025_tagger_tagger_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='minimum_sample_size',
            field=models.IntegerField(blank=True, default=50),
        ),
    ]
