# Generated by Django 2.2.24 on 2022-01-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0027_tagger_pos_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagger',
            name='analyzer',
            field=models.CharField(default='word', max_length=1000),
        ),
    ]
