image: docker.texta.ee/texta/texta-rest-base-image:latest

variables:
  # Elastic
  TEXTA_ES_URL: http://texta-elastic:9200
  # Redis
  TEXTA_REDIS_URL: redis://redis:6379
  # UAA
  TEXTA_USE_UAA: "True"
  TEXTA_UAA_REDIRECT_URI: http://localhost:8000/api/v2/uaa/callback
  TEXTA_UAA_USER: test
  TEXTA_UAA_EMAIL: test@test.com
  TEXTA_UAA_PWD: test
  TEXTA_UAA_URL: http://texta-uaa:8080/uaa
  TEXTA_UAA_FRONT_REDIRECT_URL: http://localhost:4200/oauth/uaa
  TEXTA_UAA_CLIENT_ID: login
  TEXTA_UAA_CLIENT_SECRET: loginsecret
  # For keeping plots as artifacts
  TEXTA_TEST_KEEP_PLOT_FILES: "True"
  # Set admin password for tests
  #TEXTA_ADMIN_PASSWORD: "1234"
  # MLP lang codes
  TEXTA_LANGUAGE_CODES: et,en
  TEXTA_EXTERNAL_DATA_DIR: /cache

services:
  - name: redis:latest
  - name: docker.texta.ee/texta/texta-uaa:latest
    alias: texta-uaa
  - name: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    alias: texta-elastic
    command: [ "bin/elasticsearch", "-Ediscovery.type=single-node" ]



stages:
  - test-back
  - build-test-image
  - test-and-build-front
  - build-final-image


TestBack:
  # Tests back-end locally
  before_script:
    - source activate texta-rest
    - python import_test_data.py -es $TEXTA_ES_URL
    - python migrate.py
  stage: test-back
  tags:
    - ci-test
  script:
    - sh wait-for-uaa.sh
    - python manage.py test toolkit/elastic/analyzers
  except:
    - tags


BuildTestImage:
  # Builds back image for front tests
  stage: build-test-image
  tags:
    - docker
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD docker.texta.ee  
    - docker build --compress --force-rm --no-cache -t docker.texta.ee/texta/texta-rest/test:latest -f ./docker/Dockerfile .
    - docker push docker.texta.ee/texta/texta-rest/test:latest
  only:
    - master


TestAndBuildFront:
  # Executes front pipeline
  stage: test-and-build-front
  trigger:
    project: texta/texta-rest-front
    strategy: depend
  only:
    - master

BuildFinalImage:
  # Builds final image with new front
  stage: build-final-image
  tags:
    - docker
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD docker.texta.ee
    - sh ./docker/build_and_push.sh
    - docker system prune --volumes -f
  only:
    - tags
