image: docker.texta.ee/texta/texta-rest-base-image:latest

variables:
  # Elastic
  TEXTA_ES_URL: http://texta-elastic:9200
  # Redis
  TEXTA_REDIS_URL: redis://redis:6379
  # UAA
  TEXTA_USE_UAA: "True"
  TEXTA_UAA_REDIRECT_URI: http://localhost:8000/api/v2/uaa/callback
  TEXTA_UAA_USER: test
  TEXTA_UAA_EMAIL: test@test.com
  TEXTA_UAA_PWD: test
  TEXTA_UAA_URL: http://texta-uaa:8080/uaa
  TEXTA_UAA_FRONT_REDIRECT_URL: http://localhost:4200/#/oauth/uaa
  TEXTA_UAA_CLIENT_ID: login
  TEXTA_UAA_CLIENT_SECRET: loginsecret
  # For keeping plots as artifacts
  TEXTA_TEST_KEEP_PLOT_FILES: "True"
  # Set admin password for tests
  #TEXTA_ADMIN_PASSWORD: "1234"
  # MLP lang codes
  TEXTA_LANGUAGE_CODES: et,en
  TEXTA_EXTERNAL_DATA_DIR: /cache

  # S3 components
  TEXTA_S3_ENABLED: "true"
  TEXTA_S3_HOST: $S3_HOST_URI
  TEXTA_S3_BUCKET_NAME: texta-models-test
  TEXTA_S3_ACCESS_KEY: $S3_ACCESS_KEY
  TEXTA_S3_SECRET_KEY: $S3_SECRET_KEY
  TEXTA_S3_USE_SECURE: "true"


services:
  - name: redis:6
  - name: docker.texta.ee/texta/texta-uaa:latest
    alias: texta-uaa
  - name: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    alias: texta-elastic
    command: [ "bin/elasticsearch", "-Ediscovery.type=single-node" ]

stages:
  - test-back
  - build-test-image
  - update_changelog
  - test-and-build-front
  - build-final-image


TestBack:
  # Tests back-end locally
  before_script:
    - source activate texta-rest
    # Cant use the manage.py command because the startup checks populate the stdout.
    - python -c 'from cryptography.fernet import Fernet;print(Fernet.generate_key().decode("utf8").strip())' > secret.key
    - python import_test_data.py -es $TEXTA_ES_URL
    - python migrate.py
  stage: test-back
  tags:
    - ci-test
  script:
    - sh wait-for-uaa.sh
    - python manage.py test
  except:
    - tags


BuildTestImage:
  # Builds back image for front tests
  stage: build-test-image
  tags:
    - with-docker
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD docker.texta.ee
    - docker build --compress --force-rm --no-cache -t docker.texta.ee/texta/texta-rest/test:latest -f ./docker/Dockerfile .
    - docker push docker.texta.ee/texta/texta-rest/test:latest
    - docker system prune -a
  only:
    - master

update-changelog:
  stage: update_changelog
  tags:
    - ci-update-version
  script:
    - currentVersion=$(grep -m1 '' VERSION)
    - |
      curl --header "PRIVATE-TOKEN: $TTK_GITLAB_TOKEN" --data "version=$currentVersion&branch=master" "https://git.texta.ee/api/v4/projects/77/repository/changelog"
  except:
    - tags
  only:
    - master

TestAndBuildFront:
  # Executes front pipeline
  stage: test-and-build-front
  trigger:
    project: texta/texta-rest-front
    strategy: depend
  only:
    - master

BuildFinalImage:
  # Builds final image with new front
  stage: build-final-image
  tags:
    - with-docker
  script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD docker.texta.ee
    - sh ./docker/build_and_push.sh
    - docker system prune -a
  only:
    - tags
