DEFAULT_MAX_SAMPLE_SIZE = 100000
DEFAULT_MIN_SAMPLE_SIZE = 50
DEFAULT_NEGATIVE_MULTIPLIER = 1
DEFAULT_NUM_EPOCHS = 3
DEFAULT_VALIDATION_SPLIT = 0.8
DEFAULT_LEARNING_RATE = 2e-5
DEFAULT_EPS = 1e-8
DEFAULT_MAX_LENGTH = 64
