# Generated by Django 2.2.11 on 2020-03-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlpprocessor',
            name='indices',
        ),
    ]
