# Generated by Django 2.1.15 on 2020-03-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlp', '0002_remove_mlpprocessor_indices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlpprocessor',
            name='indices',
        ),
    ]
