# Generated by Django 2.2.20 on 2021-06-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlp', '0005_applylangworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlpworker',
            name='es_scroll_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mlpworker',
            name='es_timeout',
            field=models.IntegerField(default=30),
        ),
    ]
