# Generated by Django 2.0.2 on 2019-01-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
    ]
