# Generated by Django 2.0.2 on 2019-01-23 14:21

import uuid
import os
from django.db import migrations, models
from utils.helper_functions import get_wildcard_files, create_file_path
from texta.settings import MODELS_DIR
from texta.settings import PROTECTED_MEDIA


def combine_names(apps, schema_editor):
    print()
    print()
    print('Creating new UUID field for existing Task entries..')
    Task = apps.get_model('task_manager', 'Task')
    for task in Task.objects.all():
        newuuid = uuid.uuid4()
        print('New UUID for Task: {} - {}'.format(task.id, newuuid))
        task.unique_id = newuuid
        task.save()
        print('Moving files..')
        rename_files(task)
        print()
        print()


def rename_files(task):
    try:
        id_name = 'model_{}'.format(task.id)
        uuid_name = 'model_{}'.format(task.unique_id)

        file_path = os.path.join(MODELS_DIR, id_name)
        media_path = os.path.join(PROTECTED_MEDIA, 'task_manager/', id_name)

        model_files = get_wildcard_files(file_path)
        media_files = get_wildcard_files(media_path)
        num_modelfiles_moved = 0
        for path, filename in model_files:
            if os.path.exists(path):
                move_model_files(path, filename, task, id_name, uuid_name)
                num_modelfiles_moved += 1
        print('Moved {} model files for Task: {}!'.format(num_modelfiles_moved, task.id))

        num_mediafiles_moved = 0
        for path, filename in media_files:
            if os.path.exists(path):
                move_media_files(path, filename, task, id_name, uuid_name)
                num_mediafiles_moved += 1
        print('Moved {} media files for Task: {}!'.format(num_mediafiles_moved, task.id))

    except Exception as e:
        print('Exception occurred on Task: {}'.format(task.id))
        print(e)


def move_model_files(path, filename, task, id_name, uuid_name):
    new_filename = filename.replace(id_name, uuid_name, 1)
    new_path = create_file_path(new_filename, MODELS_DIR, task.task_type)
    # Move file
    os.rename(path, new_path)


def move_media_files(path, filename, task, id_name, uuid_name):
    new_filename = filename.replace(id_name, uuid_name, 1)
    new_path = create_file_path(new_filename, PROTECTED_MEDIA, 'task_manager/', task.task_type)
    # Move file
    os.rename(path, new_path)


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20190123_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),

        migrations.RunPython(combine_names),

        migrations.AlterField(
            model_name='task',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
