# Generated by Django 2.1.7 on 2019-04-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_task_resources'),
        ('task_manager', '0003_parameters_datasets'),
    ]

    operations = [
    ]
