# Generated by Django 2.2.19 on 2021-04-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bert_tagger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berttagger',
            name='balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='berttagger',
            name='balance_to_max_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='berttagger',
            name='use_sentence_shuffle',
            field=models.BooleanField(default=False),
        ),
    ]
