# Generated by Django 2.2.23 on 2021-06-17 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bert_tagger', '0002_auto_20210416_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='berttagger',
            name='checkpoint_model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bert_tagger.BertTagger'),
        ),
        migrations.AlterField(
            model_name='berttagger',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
