# Generated by Django 2.2.24 on 2021-09-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bert_tagger', '0004_berttagger_pos_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berttagger',
            name='model',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='', verbose_name=''),
        ),
    ]
