# Generated by Django 2.2.28 on 2022-05-20 12:12

from django.db import migrations, models
import json


def convert_num_examples_to_classes(apps, schema_editor):
    BertTagger = apps.get_model("bert_tagger", "BertTagger")
    for tagger in BertTagger.objects.all():
        classes = list(json.loads(tagger.num_examples).keys())
        tagger.classes = json.dumps(classes, ensure_ascii=False)
        tagger.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bert_tagger', '0006_berttagger_use_gpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='berttagger',
            name='classes',
            field=models.TextField(default='[]'),
        ),
        migrations.RunPython(convert_num_examples_to_classes)
    ]
