# Generated by Django 2.2.28 on 2022-06-28 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bert_tagger', '0007_berttagger_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='berttagger',
            name='favorited_users',
            field=models.ManyToManyField(related_name='bert_tagger_berttagger_favorited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
