# Generated by Django 2.2.28 on 2022-08-08 11:39

from django.db import migrations, models


def transfer_bert_tagger_tasks(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    BertTagger = apps.get_model('bert_tagger', 'BertTagger')
    for orm in BertTagger.objects.filter(task__isnull=False):
        task = getattr(orm, "task", None)
        if task:
            orm.tasks.add(orm.task)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_make_last_update_automatic'),
        ('bert_tagger', '0008_berttagger_favorited_users'),
    ]

    operations = [

        migrations.AddField(
            model_name='berttagger',
            name='tasks',
            field=models.ManyToManyField(to='core.Task'),
        ),

        migrations.RunPython(transfer_bert_tagger_tasks),

        migrations.RemoveField(
            model_name='berttagger',
            name='task',
        ),

        migrations.AlterField(
            model_name='berttagger',
            name='description',
            field=models.CharField(help_text='Description of the task to distinguish it from others.', max_length=1000),
        ),
    ]
