# Generated by Django 2.2.14 on 2020-08-17 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_project_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('replace_misspelled_names', models.BooleanField(default=True)),
                ('replace_single_last_names', models.BooleanField(default=True)),
                ('replace_single_first_names', models.BooleanField(default=True)),
                ('misspelling_threshold', models.FloatField(default=0.9)),
                ('mimic_casing', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
        ),
    ]
