# Generated by Django 2.2.15 on 2020-09-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymizer',
            name='auto_adjust_threshold',
            field=models.BooleanField(default=False),
        ),
    ]
