# Generated by Django 2.0.4 on 2019-01-10 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lexicon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=100)),
                ('lexicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon_miner.Lexicon')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wrd', models.CharField(max_length=100)),
                ('lexicon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon_miner.Lexicon')),
                ('suggestionset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lexicon_miner.SuggestionSet')),
            ],
        ),
    ]
