# Generated by Django 2.2.25 on 2022-01-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_labelset_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelset',
            name='fact_names',
            field=models.TextField(default='[]', null=True),
        ),
    ]
