# Generated by Django 2.2.26 on 2022-02-08 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_task_task_type'),
        ('annotator', '0005_labelset_value_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task'),
        ),
    ]
