# Generated by Django 2.2.26 on 2022-02-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0006_annotator_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='add_facts_mapping',
            field=models.BooleanField(default=False),
        ),
    ]
