# Generated by Django 2.2.28 on 2022-04-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0008_auto_20220217_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='annotator_uid',
            field=models.CharField(default='', help_text='Unique Identifier for Annotator', max_length=100),
        ),
    ]
