# Generated by Django 2.2.28 on 2022-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='add_misclassified_examples',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='token_based',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
