# Generated by Django 2.2.28 on 2022-05-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_auto_20220523_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='misclassified_examples',
            field=models.TextField(default='{}'),
        ),
    ]
