# Generated by Django 2.2.28 on 2022-09-05 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluator', '0003_reformat_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='favorited_users',
            field=models.ManyToManyField(related_name='evaluator_evaluator_favorited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
