# Generated by Django 2.2.28 on 2022-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0003_evaluator_misclassified_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='field',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
