# Generated by Django 2.1.7 on 2020-01-29 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL)
    ]

    operations = [
        migrations.CreateModel(
            name='TorchTagger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('fields', models.TextField(default='[]')),
                ('query', models.TextField(default='{"query": {"match_all": {}}}')),
                ('fact_name', models.CharField(max_length=1000, null=True)),
                ('minimum_sample_size', models.IntegerField(default=50)),
                ('model_architecture', models.CharField(default='TextRNN', max_length=10)),
                ('num_epochs', models.IntegerField(default=5)),
                ('validation_ratio', models.FloatField(default=0.8)),
                ('negative_multiplier', models.FloatField(default=1)),
                ('maximum_sample_size', models.IntegerField(default=100000)),
                ('label_index', models.TextField(default='{}')),
                ('epoch_reports', models.TextField(default='[]')),
                ('accuracy', models.FloatField(default=None, null=True)),
                ('training_loss', models.FloatField(default=None, null=True)),
                ('precision', models.FloatField(default=None, null=True)),
                ('recall', models.FloatField(default=None, null=True)),
                ('f1_score', models.FloatField(default=None, null=True)),
                ('model', models.FileField(default=None, null=True, upload_to='', verbose_name='')),
                ('text_field', models.FileField(default=None, null=True, upload_to='', verbose_name='')),
                ('plot', models.FileField(null=True, upload_to='data/media', verbose_name='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('embedding', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='embedding.Embedding')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
                ('task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task')),
            ],
        ),
    ]
