# Generated by Django 2.1.7 on 2019-11-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torchtagger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchtagger',
            name='minimum_sample_size',
            field=models.IntegerField(default=50),
        ),
    ]
