# Generated by Django 2.1.15 on 2020-03-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torchtagger', '0003_rename_paths_to_relative'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchtagger',
            name='tokenize',
            field=models.BooleanField(default=False),
        ),
    ]
