# Generated by Django 2.1.15 on 2020-03-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchtagger', '0004_torchtagger_tokenize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torchtagger',
            name='text_field',
        ),
    ]
