# Generated by Django 2.2.19 on 2021-04-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torchtagger', '0006_auto_20210420_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchtagger',
            name='num_examples',
            field=models.TextField(default='{}', null=True),
        ),
    ]
