# Generated by Django 2.2.19 on 2021-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torchtagger', '0007_torchtagger_num_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchtagger',
            name='pos_label',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
