# Generated by Django 2.2.28 on 2022-06-28 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('torchtagger', '0010_torchtagger_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchtagger',
            name='favorited_users',
            field=models.ManyToManyField(related_name='torchtagger_torchtagger_favorited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
