# Generated by Django 2.2.28 on 2022-08-10 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def transfer_torchtagger_tasks(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    TorchTagger = apps.get_model('torchtagger', 'TorchTagger')
    for orm in TorchTagger.objects.filter(task__isnull=False):
        task = getattr(orm, "task", None)
        if task:
            orm.tasks.add(orm.task)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_make_last_update_automatic'),
        ('torchtagger', '0011_torchtagger_favorited_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchtagger',
            name='tasks',
            field=models.ManyToManyField(to='core.Task'),
        ),

        migrations.RunPython(transfer_torchtagger_tasks),

        migrations.RemoveField(
            model_name='torchtagger',
            name='task',
        ),

        migrations.AlterField(
            model_name='torchtagger',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='torchtagger',
            name='description',
            field=models.CharField(help_text='Description of the task to distinguish it from others.', max_length=1000),
        ),
    ]
