# Generated by Django 2.1.7 on 2019-05-13 12:46

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('indices', multiselectfield.db.fields.MultiSelectField(default=None, max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile')),
                ('users', models.ManyToManyField(related_name='project_users', to='user_profile.UserProfile')),
            ],
        ),
    ]
