# Generated by Django 2.1.15 on 2020-04-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0010_auto_20200312_1804'),
        ('topic_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusteringresult',
            name='embedding',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='embedding.Embedding'),
        ),
    ]
