# Generated by Django 2.1.15 on 2020-04-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteringresult',
            name='vectorizer',
            field=models.TextField(default='TfIdf Vectorizer'),
        ),
    ]
