# Generated by Django 2.1.15 on 2020-04-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_analyzer', '0002_auto_20200409_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='original_text_field',
        ),
        migrations.RemoveField(
            model_name='clusteringresult',
            name='original_text_field',
        ),
        migrations.AddField(
            model_name='cluster',
            name='display_fields',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='clusteringresult',
            name='display_fields',
            field=models.TextField(default='[]'),
        ),
    ]
