DEFAULT_OVERWRITE_EXISTING_STOPWORDS = True
DEFAULT_BULK_SIZE = 100
DEFAULT_ES_TIMEOUT = 10
DEFAULT_ADD_SPANS = False
DEFAULT_DISTANCE_METHOD_CHOICES = ["editdistance", "fasttext"]
DEFAULT_DISTANCE_METHOD = DEFAULT_DISTANCE_METHOD_CHOICES[0]
