from texta_lexicon_matcher.lexicon_matcher import SUPPORTED_MATCH_TYPES, SUPPORTED_OPERATORS

PRIORITY_CHOICES = (
    ("first_span", "first_span"),
    ("last_span", "last_span"),
)

MATCH_TYPE_CHOICES = [(match_type, match_type) for match_type in SUPPORTED_MATCH_TYPES]
OPERATOR_CHOICES = [(operator, operator) for operator in SUPPORTED_OPERATORS]

DEFAULT_OPERATOR = SUPPORTED_OPERATORS[0]
DEFAULT_MATCH_TYPE = SUPPORTED_MATCH_TYPES[0]

DEFAULT_REQUIRED_WORDS = 1.0
DEFAULT_PHRASE_SLOP = 0
DEFAULT_COUNTER_SLOP = 0
DEFAULT_N_ALLOWED_EDITS = 0
DEFAULT_RETURN_FUZZY_MATCH = True
DEFAULT_IGNORE_CASE = True
DEFAULT_IGNORE_PUNCTUATION = True

DEFAULT_ADD_SPANS = True
