# Generated by Django 2.2.20 on 2021-05-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarizer',
            name='ratio',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
