# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run_description', models.CharField(max_length=200)),
                ('num_dimensions', models.IntegerField()),
                ('num_workers', models.IntegerField()),
                ('min_freq', models.IntegerField()),
                ('run_status', models.CharField(max_length=200)),
                ('run_started', models.DateTimeField()),
                ('run_completed', models.DateTimeField(blank=True, null=True)),
                ('lexicon_size', models.IntegerField(blank=True, null=True)),
                ('search', models.TextField(blank=True, null=True)),
                ('fields', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
