# Generated by Django 2.1.7 on 2019-11-14 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_search_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reindexer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('query', models.TextField(default='{"query": {"match_all": {}}}')),
                ('indices', models.TextField(default='[]')),
                ('fields', models.TextField(default='[]')),
                ('new_index', models.CharField(default='', max_length=100)),
                ('random_size', models.IntegerField(default=0)),
                ('field_type', models.TextField(default='[]')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
                ('task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task')),
            ],
        ),
    ]
