# Generated by Django 2.2.11 on 2020-03-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0002_auto_20191121_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
