# Generated by Django 2.2.17 on 2021-01-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0004_reindexer_add_facts_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='reindexer',
            name='scroll_size',
            field=models.IntegerField(default=500),
        ),
    ]
