# Generated by Django 2.2.17 on 2021-01-29 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20210126_1041'),
        ('elastic', '0005_reindexer_scroll_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSplitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=1000)),
                ('scroll_size', models.IntegerField(default=500)),
                ('query', models.TextField(default='{"query": {"match_all": {}}}')),
                ('fields', models.TextField(default='[]')),
                ('train_index', models.CharField(default='', max_length=1000)),
                ('test_index', models.CharField(default='', max_length=1000)),
                ('fact', models.CharField(max_length=1000, null=True)),
                ('test_size', models.IntegerField(default=20)),
                ('distribution', models.TextField(default='original')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('indices', models.ManyToManyField(to='elastic.Index')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
                ('task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task')),
            ],
        ),
    ]
