# Generated by Django 2.2.18 on 2021-02-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0006_indexsplitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexsplitter',
            name='custom_distribution',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='indexsplitter',
            name='distribution',
            field=models.TextField(default='random'),
        ),
        migrations.AlterField(
            model_name='indexsplitter',
            name='fact',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
