# Generated by Django 2.2.18 on 2021-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0007_auto_20210204_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexsplitter',
            name='str_val',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
