# Generated by Django 2.2.22 on 2021-05-18 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elastic', '0009_searchfieldstagger_searchquerytagger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyStemmerWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('query', models.TextField(default='{"query": {"match_all": {}}}')),
                ('stemmer_lang', models.CharField(max_length=1000, null=True)),
                ('fields', models.TextField(default='[]')),
                ('detect_lang', models.BooleanField()),
                ('es_timeout', models.IntegerField(default=15, help_text='How many minutes should there be between scroll requests before triggering a timeout.')),
                ('bulk_size', models.IntegerField(default=100, help_text='How many documents should be returned by Elasticsearch with each request.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('indices', models.ManyToManyField(to='elastic.Index')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
                ('task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task')),
            ],
        ),
    ]
