# Generated by Django 2.2.20 on 2021-05-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0010_applystemmerworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchfieldstagger',
            name='bulk_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='searchfieldstagger',
            name='es_timeout',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='searchquerytagger',
            name='bulk_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='searchquerytagger',
            name='es_timeout',
            field=models.IntegerField(default=10),
        ),
    ]
