# Generated by Django 2.2.20 on 2021-05-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0011_auto_20210518_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='added_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='index',
            name='client',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='index',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='index',
            name='domain',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='index',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='index',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
