# Generated by Django 2.2.23 on 2021-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0013_auto_20210616_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
