# Generated by Django 2.2.28 on 2022-08-10 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def transfer_query_tagger_tasks(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SearchQueryTagger = apps.get_model('elastic', 'SearchQueryTagger')
    for orm in SearchQueryTagger.objects.filter(task__isnull=False):
        task = getattr(orm, "task", None)
        if task:
            orm.tasks.add(orm.task)


def transfer_field_tagger_tasks(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SearchFieldsTagger = apps.get_model('elastic', 'SearchFieldsTagger')
    for orm in SearchFieldsTagger.objects.filter(task__isnull=False):
        task = getattr(orm, "task", None)
        if task:
            orm.tasks.add(orm.task)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_make_last_update_automatic'),
        ('elastic', '0017_reindexer_tasks_reformat'),
    ]

    operations = [

        migrations.AddField(
            model_name='searchfieldstagger',
            name='tasks',
            field=models.ManyToManyField(to='core.Task'),
        ),
        migrations.AddField(
            model_name='searchquerytagger',
            name='tasks',
            field=models.ManyToManyField(to='core.Task'),
        ),

        migrations.RunPython(transfer_query_tagger_tasks),
        migrations.RunPython(transfer_field_tagger_tasks),


        migrations.RemoveField(
            model_name='searchfieldstagger',
            name='task',
        ),
        migrations.RemoveField(
            model_name='searchquerytagger',
            name='task',
        ),

        migrations.AlterField(
            model_name='reindexer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reindexer',
            name='description',
            field=models.CharField(help_text='Description of the task to distinguish it from others.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='searchfieldstagger',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchfieldstagger',
            name='description',
            field=models.CharField(help_text='Description of the task to distinguish it from others.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='searchquerytagger',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchquerytagger',
            name='description',
            field=models.CharField(help_text='Description of the task to distinguish it from others.', max_length=1000),
        ),
    ]
