# Generated by Django 2.2.28 on 2022-08-10 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def transfer_delete_facts_tasks(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    DeleteFactsByQueryTask = apps.get_model('elastic', 'DeleteFactsByQueryTask')
    for orm in DeleteFactsByQueryTask.objects.filter(task__isnull=False):
        task = getattr(orm, "task", None)
        if task:
            orm.tasks.add(orm.task)


def transfer_edit_facts_tasks(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    EditFactsByQueryTask = apps.get_model('elastic', 'EditFactsByQueryTask')
    for orm in EditFactsByQueryTask.objects.filter(task__isnull=False):
        task = getattr(orm, "task", None)
        if task:
            orm.tasks.add(orm.task)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_make_last_update_automatic'),
        ('elastic', '0019_indexsplitter_tasks_reformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletefactsbyquerytask',
            name='tasks',
            field=models.ManyToManyField(to='core.Task'),
        ),
        migrations.AddField(
            model_name='editfactsbyquerytask',
            name='tasks',
            field=models.ManyToManyField(to='core.Task'),
        ),

        migrations.RunPython(transfer_edit_facts_tasks),
        migrations.RunPython(transfer_delete_facts_tasks),

        migrations.RemoveField(
            model_name='deletefactsbyquerytask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='editfactsbyquerytask',
            name='task',
        ),

        migrations.AlterField(
            model_name='deletefactsbyquerytask',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deletefactsbyquerytask',
            name='description',
            field=models.CharField(help_text='Description of the task to distinguish it from others.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='editfactsbyquerytask',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='editfactsbyquerytask',
            name='description',
            field=models.CharField(help_text='Description of the task to distinguish it from others.', max_length=1000),
        ),
    ]
