# Generated by Django 2.1.13 on 2019-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='embeddingcluster',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
