# Generated by Django 2.1.14 on 2019-11-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('embedding', '0001_initial_squashed_0002_auto_20191121_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='embedding_model',
            field=models.FileField(default=None, null=True, upload_to='data/models/embedding', verbose_name=''),
        ),

        migrations.AddField(
            model_name='embedding',
            name='phraser_model',
            field=models.FileField(default=None, null=True, upload_to='data/models/embedding', verbose_name=''),
        ),

        migrations.AddField(
            model_name='embeddingcluster',
            name='cluster_model',
            field=models.FileField(default=None, null=True, upload_to='data/models/embedding', verbose_name=''),
        ),

    ]
