# Generated by Django 2.1.14 on 2019-11-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0004_migrate_model_path_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embedding',
            name='location',
        ),

        migrations.RemoveField(
            model_name='embeddingcluster',
            name='location',
        )
    ]
