# Generated by Django 2.1.13 on 2019-11-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0005_remove_model_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='max_documents',
            field=models.IntegerField(default=0),
        ),
    ]
