# Generated by Django 2.2.11 on 2020-03-09 15:50
import json

from django.db import migrations, models


def data_migration(apps, schema_editor):
    Embedding = apps.get_model('embedding', 'Embedding')
    for embedding in Embedding.objects.all():
        indices = list(embedding.indices)
        embedding.keeper = json.dumps(indices)
        embedding.save()


def final_solution(apps, schema_editor):
    Embedding = apps.get_model('embedding', 'Embedding')
    Index = apps.get_model('elastic', 'Index')

    for embedding in Embedding.objects.all():
        indices = json.loads(embedding.keeper)
        for index_name in indices:
            i, is_created = Index.objects.get_or_create(name=index_name)
            embedding.indices.add(i)
        embedding.save()


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0003_index'),
        ('embedding', '0008_auto_20200129_0950'),
    ]

    operations = [

        migrations.AddField(
            model_name='embedding',
            name='keeper',
            field=models.TextField(default="[]"),
        ),


        migrations.RunPython(data_migration),


        migrations.RemoveField(
            model_name='embedding',
            name='indices',
        ),

        migrations.AddField(
            model_name='embedding',
            name='indices',
            field=models.ManyToManyField(to='elastic.Index'),
        ),

        migrations.RunPython(final_solution),

        migrations.RemoveField(
            model_name='embedding',
            name='keeper',
        ),
    ]
