# Generated by Django 2.2.11 on 2020-03-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0003_index'),
        ('embedding', '0008_auto_20200129_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embedding',
            name='indices',
        ),
        migrations.AddField(
            model_name='embedding',
            name='indices',
            field=models.ManyToManyField(to='elastic.Index'),
        ),
    ]
