# Generated by Django 2.2.24 on 2021-10-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0015_embedding_snowball_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='num_epochs',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='embedding',
            name='window_size',
            field=models.IntegerField(default=1),
        ),
    ]
