# Generated by Django 2.2.28 on 2022-06-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0016_auto_20211006_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='stop_words',
            field=models.TextField(default='[]'),
        ),
    ]
