# Generated by Django 2.2.28 on 2022-06-28 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('embedding', '0017_embedding_stop_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='favorited_users',
            field=models.ManyToManyField(related_name='embedding_embedding_favorited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
