# Generated by Django 2.0.2 on 2019-01-29 14:03

from django.db import migrations, models
import django.db.models.deletion
import json
from texta.settings import MIGRATION_LOGGER
import logging


def to_multiindex(apps, schema_editor):
    logging.getLogger(MIGRATION_LOGGER).info(json.dumps({'process':'to_multiindex', 'info': 'Changing Dataset field to Datasets field.'}))

    Search = apps.get_model('searcher', 'Search')
    for search in Search.objects.all():
        logging.getLogger(MIGRATION_LOGGER).info(json.dumps({'process':'to_multiindex', 'info': 'Search changed to multiindex', 'pk': search.id, 'desc': search.description}))
        search.datasets.set([search.dataset])
        search.save()



class Migration(migrations.Migration):

    dependencies = [
        ('permission_admin', '0001_initial'),
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='datasets',
            field=models.ManyToManyField(to='permission_admin.Dataset'),
        ),

        migrations.RunPython(to_multiindex),

        migrations.RemoveField(
            model_name='search',
            name='dataset',
        ),
    ]
