# Generated by Django 2.1.13 on 2019-10-10 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('embedding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neurotagger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('fields', models.TextField(default='[]')),
                ('queries', models.TextField(default='[]')),
                ('fact_name', models.CharField(blank=True, max_length=100)),
                ('fact_values', models.TextField(blank=True)),
                ('model_architecture', models.CharField(choices=[('fnn', 'fnn'), ('cnn', 'cnn'), ('gru', 'gru'), ('lstm', 'lstm'), ('gruCNN', 'gruCNN'), ('lstmCNN', 'lstmCNN')], max_length=10)),
                ('seq_len', models.IntegerField(default=150)),
                ('vocab_size', models.IntegerField(default=30000)),
                ('num_epochs', models.IntegerField(default=5)),
                ('validation_split', models.FloatField(default=0.2)),
                ('negative_multiplier', models.FloatField(blank=True, default=1.0)),
                ('maximum_sample_size', models.IntegerField(blank=True, default=10000)),
                ('min_fact_doc_count', models.IntegerField(blank=True, default=50)),
                ('max_fact_doc_count', models.IntegerField(blank=True, null=True)),
                ('score_threshold', models.FloatField(blank=True, default=0.0)),
                ('validation_accuracy', models.FloatField(default=None, null=True)),
                ('training_accuracy', models.FloatField(default=None, null=True)),
                ('training_loss', models.FloatField(default=None, null=True)),
                ('validation_loss', models.FloatField(default=None, null=True)),
                ('classification_report', models.TextField(blank=True)),
                ('location', models.TextField()),
                ('model_plot', models.FileField(null=True, upload_to='media', verbose_name='')),
                ('plot', models.FileField(null=True, upload_to='media', verbose_name='')),
                ('result_json', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('embedding', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='embedding.Embedding')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
                ('task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task')),
            ],
        ),
    ]
