# Generated by Django 2.1.7 on 2019-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurotagger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neurotagger',
            name='model_plot',
        ),
        migrations.AlterField(
            model_name='neurotagger',
            name='plot',
            field=models.FileField(null=True, upload_to='data/media', verbose_name=''),
        ),
    ]
