# Generated by Django 2.1.13 on 2019-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurotagger', '0002_auto_20191021_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neurotagger',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='neurotagger',
            name='fact_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
