# Generated by Django 2.1.14 on 2019-11-29 07:22
import json

from django.db import migrations


def transfer_existing_model_paths(apps, schema_editor):
    """
    Iterating through objects.all() is pretty expensive usually
    as it makes multiple queries to the DB but in this case it cant
    be helped.
    """
    neurotaggers = apps.get_model("neurotagger", "Neurotagger")
    for neurotagger in neurotaggers.objects.all():
        if neurotagger.location:
            model_path = json.loads(neurotagger.location)["model"]
            tokenizer_model_path = json.loads(neurotagger.location)["tokenizer_model"]
            tokenizer_vocab_path = json.loads(neurotagger.location)["tokenizer_vocab"]

            neurotagger.model = model_path
            neurotagger.tokenizer_model.name = tokenizer_model_path
            neurotagger.tokenizer_vocab.name = tokenizer_vocab_path
            neurotagger.save()
        else:
            neurotagger.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('neurotagger', '0004_add_model_path_fields'),
    ]

    operations = [
        migrations.RunPython(transfer_existing_model_paths)
    ]
