# Generated by Django 2.1.14 on 2019-12-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurotagger', '0005_migrate_models_path_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neurotagger',
            name='location'
        )
    ]
