# Generated by Django 2.1.7 on 2019-12-16 11:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neurotagger', '0006_change_model_path_char_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='neurotagger',
            name='indices',
            field=multiselectfield.db.fields.MultiSelectField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='neurotagger',
            name='model',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='neurotagger',
            name='plot',
            field=models.FileField(max_length=300, null=True, upload_to='data/media', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='neurotagger',
            name='tokenizer_model',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='neurotagger',
            name='tokenizer_vocab',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='', verbose_name=''),
        ),
    ]
