# Generated by Django 2.1.7 on 2019-05-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lexicon', '0001_initial'),
        ('user_profile', '0001_initial'),
        ('phrase', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicon',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='lexicon',
            name='phrases',
            field=models.ManyToManyField(to='phrase.Phrase'),
        ),
        migrations.AddField(
            model_name='lexicon',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
