# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permission_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('json', models.CharField(max_length=2048)),
                ('last_modified', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission_admin.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=64)),
                ('content', models.CharField(blank=True, max_length=512, null=True)),
                ('layer', models.CharField(blank=True, max_length=64, null=True)),
                ('join_by', models.CharField(blank=True, max_length=32, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_components', to=settings.AUTH_USER_MODEL)),
                ('sub_components', models.ManyToManyField(to='grammar_builder.GrammarComponent')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarPageMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search_id', models.IntegerField()),
                ('inclusive_grammar', models.IntegerField()),
                ('exclusive_grammar', models.IntegerField()),
                ('polarity', models.CharField(max_length=8)),
                ('page', models.IntegerField()),
                ('elastic_start', models.IntegerField()),
                ('elastic_end', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
