# Generated by Django 2.2 on 2019-10-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_result_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='query',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
