# Generated by Django 2.1.13 on 2019-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_search_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexicon',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='search',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='errors',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='result_hash',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='step',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
