# Generated by Django 2.1.14 on 2019-12-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_increase_desc_len'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
