# Generated by Django 2.1.7 on 2020-01-29 07:50

from django.db import migrations
import toolkit.multiselectfield


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_result_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='indices',
            field=toolkit.multiselectfield.PatchedMultiSelectField(default=None, max_length=200),
        ),
    ]
