# Generated by Django 2.1.15 on 2020-03-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200309_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
    ]
