# Generated by Django 2.1.15 on 2020-03-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_corevariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevariable',
            name='value',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
