# Generated by Django 2.2.17 on 2021-01-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexicon',
            name='discarded_phrases',
        ),
        migrations.RemoveField(
            model_name='lexicon',
            name='phrases',
        ),
        migrations.AddField(
            model_name='lexicon',
            name='negatives_unused',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='lexicon',
            name='negatives_used',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='lexicon',
            name='positives_unused',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='lexicon',
            name='positives_used',
            field=models.TextField(default='[]'),
        ),
    ]
