# Generated by Django 2.2.17 on 2021-03-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210126_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='application',
            field=models.CharField(default='toolkit', max_length=1000),
        ),
    ]
