# Generated by Django 2.2.20 on 2021-06-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scope',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
