# Generated by Django 2.2.22 on 2021-06-10 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_userprofile_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='administrators',
            field=models.ManyToManyField(related_name='administrators', to=settings.AUTH_USER_MODEL),
        ),
    ]
