# Generated by Django 2.2.22 on 2021-08-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sync_superadmin_and_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scopes',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_uaa_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scopes',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
