# Generated by Django 2.2.22 on 2021-07-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_uaa_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uaa_account_id',
            field=models.TextField(default=''),
        ),
    ]
