# Generated by Django 2.2.21 on 2021-08-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210806_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='scopes',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
