# Generated by Django 2.2.24 on 2021-10-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_name_and_uaa_changes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phrase',
        ),
    ]
