# Generated by Django 2.2.22 on 2021-08-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_name_and_uaa_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
    ]
