# Generated by Django 2.2.28 on 2022-08-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_timestamps_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
