# Generated by Django 2.2.13 on 2020-07-06 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_project_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegexTagger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('lexicon', models.TextField(default='')),
                ('counter_lexicon', models.TextField(default='')),
                ('operator', models.CharField(default='or', max_length=25)),
                ('match_type', models.CharField(default='prefix', max_length=25)),
                ('required_words', models.FloatField(default=1.0)),
                ('phrase_slop', models.IntegerField(default=0)),
                ('counter_slop', models.IntegerField(default=0)),
                ('n_allowed_edits', models.IntegerField(default=0)),
                ('return_fuzzy_match', models.BooleanField(default=True)),
                ('ignore_case', models.BooleanField(default=True)),
                ('ignore_punctuation', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
        ),
    ]
