# Generated by Django 2.2.16 on 2020-09-10 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regex_tagger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegexTaggerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
                ('regex_taggers', models.ManyToManyField(default=None, to='regex_tagger.RegexTagger')),
                ('task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task')),
            ],
        ),
    ]
