# Generated by Django 2.2.18 on 2021-02-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210126_1041'),
        ('regex_tagger', '0002_regextaggergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='regextagger',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Task'),
        ),
    ]
