# Generated by Django 2.2.28 on 2022-06-28 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regex_tagger', '0003_regextagger_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='regextagger',
            name='favorited_users',
            field=models.ManyToManyField(related_name='regex_tagger_regextagger_favorited_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regextaggergroup',
            name='favorited_users',
            field=models.ManyToManyField(related_name='regex_tagger_regextaggergroup_favorited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
